[package]
name = "3designd/networker"
version = "0.3.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.toml", "rokit.toml"]

[dependencies]

[build]
include = ["networker"]
